spring:
  data:
    rest:
      base-path: /rest/api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
