spring:
  data:
    rest:
      base-path: /rest/api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
#    username: user
#    password: secret
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE

